---

acc1-amm:
    hostname: "192.168.68.123"
    groups:
        - access
    data:
        loopback: "1.1.1.1"          

acc2-amm:
    hostname: "192.168.68.117"
    groups:
        - access
    data:
        loopback: "2.2.2.2"



    

    



